"""baseline

Revision ID: 4d729c29445a
Revises: 
Create Date: 2026-04-26 18:05:34.393288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d729c29445a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ⚠️ 안전 가드 — production/prod 에서는 절대 실행 금지 (destructive baseline).
    #   DEPLOY.md 경고와 동일한 정책을 코드 레벨에서 강제.
    #   운영 DB에는 scripts/db/migrate_live.sql 같은 additive migration만 적용.
    import os as _os
    _env = _os.getenv("ENV", "").lower()
    _allow = _os.getenv("ALLOW_DESTRUCTIVE_BASELINE", "").lower() in ("1", "true", "yes")
    if _env in ("prod", "production", "live") and not _allow:
        raise RuntimeError(
            "[SAFETY] destructive baseline (drop_table 포함) 이 "
            f"ENV={_env} 에서 실행되려 했습니다. "
            "운영 DB에는 금지. 강제 실행이 필요하면 ALLOW_DESTRUCTIVE_BASELINE=1 을 설정하세요."
        )
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('candle_bars_2028_08_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_08')
    op.drop_index(op.f('candle_bars_2028_08_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_08')
    op.drop_table('candle_bars_2028_08')
    op.drop_index(op.f('idx_ticker_symbol'), table_name='ticker_snapshots')
    op.drop_table('ticker_snapshots')
    op.drop_index(op.f('candle_bars_2026_01_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_01')
    op.drop_index(op.f('candle_bars_2026_01_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_01')
    op.drop_table('candle_bars_2026_01')
    op.drop_index(op.f('candle_bars_2028_10_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_10')
    op.drop_index(op.f('candle_bars_2028_10_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_10')
    op.drop_table('candle_bars_2028_10')
    op.drop_index(op.f('candle_bars_2028_05_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_05')
    op.drop_index(op.f('candle_bars_2028_05_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_05')
    op.drop_table('candle_bars_2028_05')
    op.drop_index(op.f('candle_bars_2028_02_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_02')
    op.drop_index(op.f('candle_bars_2028_02_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_02')
    op.drop_table('candle_bars_2028_02')
    op.drop_index(op.f('candle_bars_2028_07_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_07')
    op.drop_index(op.f('candle_bars_2028_07_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_07')
    op.drop_table('candle_bars_2028_07')
    op.drop_index(op.f('candle_bars_2026_02_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_02')
    op.drop_index(op.f('candle_bars_2026_02_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_02')
    op.drop_table('candle_bars_2026_02')
    op.drop_index(op.f('candle_bars_2028_06_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_06')
    op.drop_index(op.f('candle_bars_2028_06_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_06')
    op.drop_table('candle_bars_2028_06')
    op.drop_index(op.f('candle_bars_2026_09_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_09')
    op.drop_index(op.f('candle_bars_2026_09_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_09')
    op.drop_table('candle_bars_2026_09')
    op.drop_index(op.f('candle_bars_2026_08_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_08')
    op.drop_index(op.f('candle_bars_2026_08_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_08')
    op.drop_table('candle_bars_2026_08')
    op.drop_index(op.f('candle_bars_2026_05_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_05')
    op.drop_index(op.f('candle_bars_2026_05_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_05')
    op.drop_table('candle_bars_2026_05')
    op.drop_index(op.f('candle_bars_2028_03_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_03')
    op.drop_index(op.f('candle_bars_2028_03_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_03')
    op.drop_table('candle_bars_2028_03')
    op.drop_index(op.f('candle_bars_2026_12_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_12')
    op.drop_index(op.f('candle_bars_2026_12_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_12')
    op.drop_table('candle_bars_2026_12')
    op.drop_index(op.f('candle_bars_2026_04_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_04')
    op.drop_index(op.f('candle_bars_2026_04_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_04')
    op.drop_table('candle_bars_2026_04')
    op.drop_index(op.f('candle_bars_2028_09_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_09')
    op.drop_index(op.f('candle_bars_2028_09_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_09')
    op.drop_table('candle_bars_2028_09')
    op.drop_table('orderbook_snapshots')
    op.drop_index(op.f('candle_bars_2026_03_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_03')
    op.drop_index(op.f('candle_bars_2026_03_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_03')
    op.drop_table('candle_bars_2026_03')
    op.drop_index(op.f('candle_bars_2026_10_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_10')
    op.drop_index(op.f('candle_bars_2026_10_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_10')
    op.drop_table('candle_bars_2026_10')
    op.drop_index(op.f('idx_candles_query'), table_name='candle_bars')
    op.drop_index(op.f('idx_candles_unique'), table_name='candle_bars')
    op.drop_table('candle_bars')
    op.drop_index(op.f('candle_bars_2026_11_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_11')
    op.drop_index(op.f('candle_bars_2026_11_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_11')
    op.drop_table('candle_bars_2026_11')
    op.drop_index(op.f('candle_bars_2028_11_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_11')
    op.drop_index(op.f('candle_bars_2028_11_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_11')
    op.drop_table('candle_bars_2028_11')
    op.drop_index(op.f('candle_bars_2026_06_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_06')
    op.drop_index(op.f('candle_bars_2026_06_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_06')
    op.drop_table('candle_bars_2026_06')
    op.drop_index(op.f('candle_bars_2028_01_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_01')
    op.drop_index(op.f('candle_bars_2028_01_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_01')
    op.drop_table('candle_bars_2028_01')
    op.drop_index(op.f('candle_bars_2028_04_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_04')
    op.drop_index(op.f('candle_bars_2028_04_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_04')
    op.drop_table('candle_bars_2028_04')
    op.drop_index(op.f('candle_bars_2026_07_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2026_07')
    op.drop_index(op.f('candle_bars_2026_07_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2026_07')
    op.drop_table('candle_bars_2026_07')
    op.drop_index(op.f('candle_bars_2028_12_symbol_id_exchange_id_timeframe_open_ti_idx'), table_name='candle_bars_2028_12')
    op.drop_index(op.f('candle_bars_2028_12_symbol_id_timeframe_open_time_idx'), table_name='candle_bars_2028_12')
    op.drop_table('candle_bars_2028_12')
    op.drop_index(op.f('idx_ai_symbol'), table_name='ai_analyses')
    op.drop_index(op.f('idx_ai_user'), table_name='ai_analyses')
    op.drop_index(op.f('idx_alert_events_rule'), table_name='alert_events')
    op.drop_index(op.f('idx_alerts_symbol'), table_name='alert_rules')
    op.drop_index(op.f('idx_alerts_user_active'), table_name='alert_rules')
    op.drop_column('alert_rules', 'updated_at')
    op.drop_index(op.f('idx_drawings_layout'), table_name='chart_drawings')
    op.drop_column('chart_drawings', 'updated_at')
    op.drop_column('chart_drawings', 'created_at')
    op.drop_index(op.f('idx_layouts_user'), table_name='chart_layouts')
    op.drop_index(op.f('idx_demo_trades_user'), table_name='demo_trades')
    op.drop_index(op.f('idx_indicators_layout'), table_name='indicator_presets')
    op.drop_column('indicator_presets', 'updated_at')
    op.drop_column('indicator_presets', 'created_at')
    op.alter_column('symbols', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('idx_symbols_asset_class'), table_name='symbols')
    op.drop_index(op.f('idx_symbols_metadata'), table_name='symbols', postgresql_using='gin')
    op.drop_index(op.f('idx_symbols_search'), table_name='symbols')
    op.drop_column('symbols', 'updated_at')
    op.drop_column('symbols', 'created_at')
    op.alter_column('user_sessions', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.drop_index(op.f('idx_sessions_user'), table_name='user_sessions')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_column('watchlist_items', 'created_at')
    op.drop_index(op.f('idx_watchlists_user'), table_name='watchlists')
    op.drop_column('watchlists', 'updated_at')
    op.drop_column('watchlists', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('watchlists', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_watchlists_user'), 'watchlists', ['user_id'], unique=False)
    op.add_column('watchlist_items', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_sessions_user'), 'user_sessions', ['user_id'], unique=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.add_column('symbols', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('symbols', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_symbols_search'), 'symbols', ['symbol_code', 'base_asset'], unique=False)
    op.create_index(op.f('idx_symbols_metadata'), 'symbols', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_symbols_asset_class'), 'symbols', ['asset_class'], unique=False)
    op.alter_column('symbols', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.add_column('indicator_presets', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('indicator_presets', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_indicators_layout'), 'indicator_presets', ['layout_id'], unique=False)
    op.create_index(op.f('idx_demo_trades_user'), 'demo_trades', ['user_id', sa.literal_column('opened_at DESC')], unique=False)
    op.create_index(op.f('idx_layouts_user'), 'chart_layouts', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.add_column('chart_drawings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('chart_drawings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_drawings_layout'), 'chart_drawings', ['layout_id'], unique=False)
    op.add_column('alert_rules', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_alerts_user_active'), 'alert_rules', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_alerts_symbol'), 'alert_rules', ['symbol_id'], unique=False)
    op.create_index(op.f('idx_alert_events_rule'), 'alert_events', ['alert_rule_id', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index(op.f('idx_ai_user'), 'ai_analyses', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_ai_symbol'), 'ai_analyses', ['symbol_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('candle_bars_2028_12',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_12_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_12_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_12', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_12_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_12', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_07',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_07_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_07_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_07', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_07_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_07', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_04',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_04_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_04_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_04', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_04_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_04', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_01',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_01_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_01_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_01', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_01_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_01', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_06',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_06_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_06_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_06', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_06_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_06', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_11',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_11_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_11_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_11', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_11_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_11', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_11',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_11_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_11_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_11', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_11_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_11', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_pkey'))
    )
    op.create_index(op.f('idx_candles_unique'), 'candle_bars', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_index(op.f('idx_candles_query'), 'candle_bars', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_table('candle_bars_2026_10',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_10_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_10_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_10', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_10_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_10', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_03',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_03_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_03_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_03', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_03_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_03', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('asks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('bids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('snapshot_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('orderbook_snapshots_pkey'))
    )
    op.create_table('candle_bars_2028_09',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_09_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_09_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_09', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_09_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_09', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_04',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_04_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_04_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_04', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_04_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_04', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_12',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_12_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_12_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_12', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_12_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_12', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_03',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_03_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_03_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_03', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_03_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_03', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_05',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_05_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_05_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_05', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_05_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_05', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_08',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_08_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_08_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_08', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_08_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_08', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_09',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_09_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_09_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_09', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_09_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_09', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_06',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_06_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_06_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_06', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_06_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_06', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_02',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_02_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_02_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_02', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_02_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_02', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_07',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_07_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_07_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_07', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_07_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_07', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_02',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_02_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_02_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_02', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_02_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_02', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_05',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_05_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_05_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_05', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_05_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_05', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2028_10',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_10_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_10_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_10', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_10_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_10', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('candle_bars_2026_01',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2026_01_pkey'))
    )
    op.create_index(op.f('candle_bars_2026_01_symbol_id_timeframe_open_time_idx'), 'candle_bars_2026_01', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2026_01_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2026_01', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    op.create_table('ticker_snapshots',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('last_price', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('change_24h', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=True),
    sa.Column('change_rate_24h', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('high_24h', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=True),
    sa.Column('low_24h', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=True),
    sa.Column('volume_24h', sa.NUMERIC(precision=38, scale=12), autoincrement=False, nullable=True),
    sa.Column('snapshot_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ticker_snapshots_pkey'))
    )
    op.create_index(op.f('idx_ticker_symbol'), 'ticker_snapshots', ['symbol_id', sa.literal_column('snapshot_time DESC')], unique=False)
    op.create_table('candle_bars_2028_08',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('symbol_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), autoincrement=False, nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=38, scale=12), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('trade_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_final', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'open_time', name=op.f('candle_bars_2028_08_pkey'))
    )
    op.create_index(op.f('candle_bars_2028_08_symbol_id_timeframe_open_time_idx'), 'candle_bars_2028_08', ['symbol_id', 'timeframe', sa.literal_column('open_time DESC')], unique=False)
    op.create_index(op.f('candle_bars_2028_08_symbol_id_exchange_id_timeframe_open_ti_idx'), 'candle_bars_2028_08', ['symbol_id', 'exchange_id', 'timeframe', 'open_time'], unique=True)
    # ### end Alembic commands ###
