"""BitMart TradFi 종목 한/영 표시명 보강 사전 (방식 C).

BitMart 계약 base 코드는 티커라 화면에 그대로 나오면 불친절하다. 주요 종목의
한글/영문 정식명을 매핑한다. 확신 없는 종목은 넣지 않는다(오표기 방지 — 미보강
시 티커가 그대로 노출되며, 이는 잘못된 이름보다 낫다).

키: 전체 심볼 코드(예: 'AAPLUSDT', 'CVXSTOCKUSDT'), 값: (한글명, 영문명)
"""

EXTRA_STOCK_NAMES: dict[str, tuple[str, str]] = {
    # ── 미국 대형주 ──
    'AALUSDT': ('아메리칸항공', 'American Airlines'),
    'AAOIUSDT': ('어플라이드옵토', 'Applied Optoelectronics'),
    'ABBVUSDT': ('애브비', 'AbbVie'),
    'ABNBUSDT': ('에어비앤비', 'Airbnb'),
    'ACHRUSDT': ('아처에비에이션', 'Archer Aviation'),
    'ACNONUSDT': ('액센츄어', 'Accenture'),
    'ADBEUSDT': ('어도비', 'Adobe'),
    'ADIUSDT': ('아날로그디바이스', 'Analog Devices'),
    'ADSKUSDT': ('오토데스크', 'Autodesk'),
    'AFRMUSDT': ('어펌', 'Affirm'),
    'AKAMUSDT': ('아카마이', 'Akamai'),
    'ALBONUSDT': ('앨버말', 'Albemarle'),
    'AMATUSDT': ('어플라이드머티리얼즈', 'Applied Materials'),
    'AMCUSDT': ('AMC엔터테인먼트', 'AMC Entertainment'),
    'AMDUSDT': ('AMD', 'Advanced Micro Devices'),
    'AMGNUSDT': ('암젠', 'Amgen'),
    'AMZNUSDT': ('아마존', 'Amazon'),
    'APDUSDT': ('에어프로덕츠', 'Air Products'),
    'APLDUSDT': ('어플라이드디지털', 'Applied Digital'),
    'APPUSDT': ('앱러빈', 'AppLovin'),
    'ARMUSDT': ('ARM홀딩스', 'Arm Holdings'),
    'ASMLUSDT': ('ASML', 'ASML Holding'),
    'ASTSUSDT': ('AST스페이스모바일', 'AST SpaceMobile'),
    'AVGOUSDT': ('브로드컴', 'Broadcom'),
    'AXONUSDT': ('액손엔터프라이즈', 'Axon Enterprise'),
    'AXPUSDT': ('아메리칸익스프레스', 'American Express'),
    'BABAUSDT': ('알리바바', 'Alibaba'),
    'BACUSDT': ('뱅크오브아메리카', 'Bank of America'),
    'BAUSDT': ('보잉', 'Boeing'),
    'BKNGUSDT': ('부킹홀딩스', 'Booking Holdings'),
    'BLKUSDT': ('블랙록', 'BlackRock'),
    'BRKBUSDT': ('버크셔해서웨이B', 'Berkshire Hathaway B'),
    'BSXUSDT': ('보스턴사이언티픽', 'Boston Scientific'),
    'BTGOONUSDT': ('배릭골드', 'Barrick Gold'),
    'BUDUSDT': ('앤하이저부시', 'Anheuser-Busch InBev'),
    'BWXTUSDT': ('BWX테크놀로지스', 'BWX Technologies'),
    'BXUSDT': ('블랙스톤', 'Blackstone'),
    'CATUSDT': ('캐터필러', 'Caterpillar'),
    'CCJUSDT': ('카메코', 'Cameco'),
    'CCLUSDT': ('카니발', 'Carnival'),
    'CGNXUSDT': ('코그넥스', 'Cognex'),
    'CIENUSDT': ('시에나', 'Ciena'),
    'CLSKUSDT': ('클린스파크', 'CleanSpark'),
    'CMCSAUSDT': ('컴캐스트', 'Comcast'),
    'CMIUSDT': ('커민스', 'Cummins'),
    'COINUSDT': ('코인베이스', 'Coinbase'),
    'COPUSDT': ('코노코필립스', 'ConocoPhillips'),
    'COSTUSDT': ('코스트코', 'Costco'),
    'CPNGONUSDT': ('쿠팡', 'Coupang'),
    'CRMUSDT': ('세일즈포스', 'Salesforce'),
    'CRWDUSDT': ('크라우드스트라이크', 'CrowdStrike'),
    'CVSUSDT': ('CVS헬스', 'CVS Health'),
    'CVXSTOCKUSDT': ('셰브론', 'Chevron'),
    'DDOGUSDT': ('데이터독', 'Datadog'),
    'DELLUSDT': ('델', 'Dell Technologies'),
    'DISUSDT': ('디즈니', 'Walt Disney'),
    'DKNGUSDT': ('드래프트킹스', 'DraftKings'),
    'EBAYUSDT': ('이베이', 'eBay'),
    'ENPHONUSDT': ('엔페이즈에너지', 'Enphase Energy'),
    'EQIXONUSDT': ('에퀴닉스', 'Equinix'),
    'ETNONUSDT': ('이튼', 'Eaton'),
    'FASTUSDT': ('패스널', 'Fastenal'),
    'FCXUSDT': ('프리포트맥모란', 'Freeport-McMoRan'),
    'FIGUSDT': ('피그마', 'Figma'),
    'FLEXUSDT': ('플렉스', 'Flex'),
    'FSLRUSDT': ('퍼스트솔라', 'First Solar'),
    'FUTUUSDT': ('푸투홀딩스', 'Futu Holdings'),
    'GDUSDT': ('제너럴다이내믹스', 'General Dynamics'),
    'GEUSDT': ('GE에어로스페이스', 'GE Aerospace'),
    'GEVUSDT': ('GE버노바', 'GE Vernova'),
    'GLWUSDT': ('코닝', 'Corning'),
    'GMEUSDT': ('게임스탑', 'GameStop'),
    'GOOGLUSDT': ('알파벳(구글)', 'Alphabet'),
    'GRABUSDT': ('그랩', 'Grab Holdings'),
    'GSUSDT': ('골드만삭스', 'Goldman Sachs'),
    'HALUSDT': ('할리버튼', 'Halliburton'),
    'HDUSDT': ('홈디포', 'Home Depot'),
    'HIMSUSDT': ('힘스앤허스', 'Hims & Hers Health'),
    'HOODUSDT': ('로빈후드', 'Robinhood'),
    'HPEUSDT': ('HPE', 'Hewlett Packard Enterprise'),
    'HSBCUSDT': ('HSBC', 'HSBC Holdings'),
    'HYUNDAIUSDT': ('현대자동차', 'Hyundai Motor'),
    'IBMUSDT': ('IBM', 'IBM'),
    'INTCUSDT': ('인텔', 'Intel'),
    'INTUUSDT': ('인튜이트', 'Intuit'),
    'IONQUSDT': ('아이온큐', 'IonQ'),
    'ISRGUSDT': ('인튜이티브서지컬', 'Intuitive Surgical'),
    'JDUSDT': ('징둥닷컴', 'JD.com'),
    'JNJUSDT': ('존슨앤드존슨', 'Johnson & Johnson'),
    'JOBYUSDT': ('조비에비에이션', 'Joby Aviation'),
    'JPMUSDT': ('JP모건', 'JPMorgan Chase'),
    'KHCUSDT': ('크래프트하인즈', 'Kraft Heinz'),
    'KIOXIAUSDT': ('키옥시아', 'Kioxia'),
    'KLACUSDT': ('KLA', 'KLA Corporation'),
    'KOUSDT': ('코카콜라', 'Coca-Cola'),
    'KUAISHOUUSDT': ('콰이쇼우', 'Kuaishou'),
    'LASERTECUSDT': ('레이저텍', 'Lasertec'),
    'LENOVOUSDT': ('레노버', 'Lenovo'),
    'LINUSDT': ('린데', 'Linde'),
    'LLYUSDT': ('일라이릴리', 'Eli Lilly'),
    'LMTUSDT': ('록히드마틴', 'Lockheed Martin'),
    'LRCXUSDT': ('램리서치', 'Lam Research'),
    'LUNRUSDT': ('인튜이티브머신스', 'Intuitive Machines'),
    'MARAUSDT': ('마라홀딩스', 'MARA Holdings'),
    'MAUSDT': ('마스터카드', 'Mastercard'),
    'MCDUSDT': ('맥도날드', "McDonald's"),
    'MCHPUSDT': ('마이크로칩', 'Microchip Technology'),
    'MDBUSDT': ('몽고DB', 'MongoDB'),
    'MEITUANUSDT': ('메이퇀', 'Meituan'),
    'METAUSDT': ('메타', 'Meta Platforms'),
    'MPWRUSDT': ('모놀리식파워', 'Monolithic Power Systems'),
    'MRKUSDT': ('머크', 'Merck'),
    'MRVLUSDT': ('마벨테크놀로지', 'Marvell Technology'),
    'MSFTUSDT': ('마이크로소프트', 'Microsoft'),
    'MSTRUSDT': ('마이크로스트래티지', 'MicroStrategy'),
    'MUUSDT': ('마이크론', 'Micron Technology'),
    'NEEUSDT': ('넥스트에라에너지', 'NextEra Energy'),
    'NFLXUSDT': ('넷플릭스', 'Netflix'),
    'NIOUSDT': ('니오', 'NIO'),
    'NKEUSDT': ('나이키', 'Nike'),
    'NOCUSDT': ('노스롭그루먼', 'Northrop Grumman'),
    'NOKSTOCKUSDT': ('노키아', 'Nokia'),
    'NOWUSDT': ('서비스나우', 'ServiceNow'),
    'NTAPUSDT': ('넷앱', 'NetApp'),
    'NUUSDT': ('누홀딩스', 'Nu Holdings'),
    'NVDAUSDT': ('엔비디아', 'NVIDIA'),
    'NVOUSDT': ('노보노디스크', 'Novo Nordisk'),
    'ORCLUSDT': ('오라클', 'Oracle'),
    'OXYUSDT': ('옥시덴탈페트롤리엄', 'Occidental Petroleum'),
    'PANWUSDT': ('팔로알토네트웍스', 'Palo Alto Networks'),
    'PAYPUSDT': ('페이팔', 'PayPal'),
    'PBRONUSDT': ('페트로브라스', 'Petrobras'),
    'PDDUSDT': ('PDD홀딩스', 'PDD Holdings'),
    'PFEUSDT': ('화이자', 'Pfizer'),
    'PGUSDT': ('P&G', 'Procter & Gamble'),
    'PLTRUSDT': ('팔란티어', 'Palantir'),
    'PYPLUSDT': ('페이팔', 'PayPal'),
    'QCOMUSDT': ('퀄컴', 'Qualcomm'),
    'QBTSUSDT': ('D-웨이브퀀텀', 'D-Wave Quantum'),
    'RDDTUSDT': ('레딧', 'Reddit'),
    'RGTIUSDT': ('리게티컴퓨팅', 'Rigetti Computing'),
    'RIOTONUSDT': ('라이엇플랫폼즈', 'Riot Platforms'),
    'RIVNUSDT': ('리비안', 'Rivian'),
    'RKLBUSDT': ('로켓랩', 'Rocket Lab'),
    'ROKUUSDT': ('로쿠', 'Roku'),
    'RTXUSDT': ('RTX', 'RTX Corporation'),
    'SAMSUNGEMUSDT': ('삼성전자', 'Samsung Electronics'),
    'SAMSUNGUSDT': ('삼성전자', 'Samsung Electronics'),
    'SATSSTOCKUSDT': ('에코스타', 'EchoStar'),
    'SBUXONUSDT': ('스타벅스', 'Starbucks'),
    'SCHWUSDT': ('찰스슈왑', 'Charles Schwab'),
    'SHOPUSDT': ('쇼피파이', 'Shopify'),
    'SKHYNIXUSDT': ('SK하이닉스', 'SK Hynix'),
    'SLBUSDT': ('슐룸버거', 'SLB'),
    'SMCIUSDT': ('슈퍼마이크로컴퓨터', 'Super Micro Computer'),
    'SMICUSDT': ('SMIC', 'Semiconductor Manufacturing International'),
    'SNOWUSDT': ('스노우플레이크', 'Snowflake'),
    'SOFTBANKUSDT': ('소프트뱅크', 'SoftBank'),
    'SONYUSDT': ('소니', 'Sony'),
    'SPGIONUSDT': ('S&P글로벌', 'S&P Global'),
    'SPOTUSDT': ('스포티파이', 'Spotify'),
    'STMUSDT': ('ST마이크로', 'STMicroelectronics'),
    'SYKUSDT': ('스트라이커', 'Stryker'),
    'TCEHYUSDT': ('텐센트', 'Tencent'),
    'TENCENTUSDT': ('텐센트', 'Tencent'),
    'TERUSDT': ('테라다인', 'Teradyne'),
    'TJXUSDT': ('TJX', 'TJX Companies'),
    'TMOUSDT': ('써모피셔', 'Thermo Fisher Scientific'),
    'TMUSUSDT': ('T모바일', 'T-Mobile US'),
    'TSLAUSDT': ('테슬라', 'Tesla'),
    'TSMUSDT': ('TSMC', 'Taiwan Semiconductor'),
    'TTWOUSDT': ('테이크투', 'Take-Two Interactive'),
    'TXNUSDT': ('텍사스인스트루먼트', 'Texas Instruments'),
    'UBERUSDT': ('우버', 'Uber'),
    'UNHUSDT': ('유나이티드헬스', 'UnitedHealth Group'),
    'UPSTUSDT': ('업스타트', 'Upstart'),
    'VRTUSDT': ('버티브', 'Vertiv'),
    'VSTUSDT': ('비스트라에너지', 'Vistra'),
    'VUSDT': ('비자', 'Visa'),
    'VZUSDT': ('버라이즌', 'Verizon'),
    'WDCUSDT': ('웨스턴디지털', 'Western Digital'),
    'WMTUSDT': ('월마트', 'Walmart'),
    'WULFUSDT': ('테라울프', 'TeraWulf'),
    'XIAOMIUSDT': ('샤오미', 'Xiaomi'),
    'XOMUSDT': ('엑슨모빌', 'ExxonMobil'),
    'ZMUSDT': ('줌', 'Zoom Communications'),
    'IRENUSDT': ('아이리스에너지', 'IREN'),
    # ── Pre-IPO / 비상장 ──
    'OPENAIUSDT': ('오픈AI', 'OpenAI'),
    'ANTHROPICUSDT': ('앤스로픽', 'Anthropic'),
    'SPACEXUSDT': ('스페이스X', 'SpaceX'),
    'SPCXUSDT': ('스페이스X', 'SpaceX'),
    'ANDURILUSDT': ('앤듀릴', 'Anduril'),
    # ── ETF ──
    'AGGUSDT': ('미국종합채권 ETF', 'iShares Core U.S. Aggregate Bond ETF'),
    'ARKKUSDT': ('ARK 이노베이션 ETF', 'ARK Innovation ETF'),
    'EEMUSDT': ('신흥국 ETF', 'iShares MSCI Emerging Markets ETF'),
    'EWHUSDT': ('홍콩 ETF', 'iShares MSCI Hong Kong ETF'),
    'EWJUSDT': ('일본 ETF', 'iShares MSCI Japan ETF'),
    'EWTUSDT': ('대만 ETF', 'iShares MSCI Taiwan ETF'),
    'EWYUSDT': ('한국 ETF', 'iShares MSCI South Korea ETF'),
    'EWZUSDT': ('브라질 ETF', 'iShares MSCI Brazil ETF'),
    'GDXUSDT': ('금광업 ETF', 'VanEck Gold Miners ETF'),
    'GLDUSDT': ('금 ETF', 'SPDR Gold Shares'),
    'IBITUSDT': ('비트코인 현물 ETF', 'iShares Bitcoin Trust'),
    'IVVUSDT': ('S&P 500 ETF', 'iShares Core S&P 500 ETF'),
    'IWMUSDT': ('러셀 2000 ETF', 'iShares Russell 2000 ETF'),
    'KWEBUSDT': ('중국 인터넷 ETF', 'KraneShares CSI China Internet ETF'),
    'LQDUSDT': ('회사채 ETF', 'iShares iBoxx IG Corp Bond ETF'),
    'QQQXUSDT': ('나스닥 100 ETF', 'Invesco QQQ'),
    'SMHUSDT': ('반도체 ETF', 'VanEck Semiconductor ETF'),
    'SOXXUSDT': ('반도체 ETF', 'iShares Semiconductor ETF'),
    'SPYXUSDT': ('S&P 500 ETF', 'SPDR S&P 500 ETF'),
    'TLTUSDT': ('장기 국채 ETF', 'iShares 20+ Year Treasury Bond ETF'),
    'VOOUSDT': ('S&P 500 ETF', 'Vanguard S&P 500 ETF'),
    'XLEUSDT': ('에너지 ETF', 'Energy Select Sector SPDR'),
    'XLFUSDT': ('금융 ETF', 'Financial Select Sector SPDR'),
    'XLKUSDT': ('기술 ETF', 'Technology Select Sector SPDR'),
    'XLUUSDT': ('유틸리티 ETF', 'Utilities Select Sector SPDR'),
}
